---
title: "RBridge_HW2"
author: "Jawaid Hakim"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Download file
# download.file("https://vincentarelbundock.github.io/Rdatasets/csv/carData/Florida.csv", destfile = 'FloridaVote.csv')

# Read from local file
votes <- read.csv("FloridaVote.csv")
summary(votes)
```


```{r}
# Bonus points: read CSV file from GitHub - use 'Raw' file URL from GitHub
v2 = read.csv("https://raw.githubusercontent.com/himalayahall/cuny-bridge-r/main/FloridaVote.csv")
summary(v2)
```


```{r}
# Define function to print  mean and median vote count for  data frame + candidate
mean_idx <- 1
median_idx <-3

#' print_mean_median
#' 
#' @param df Date frame
#' @param candidate Candidate name. Case insensitive.
#' @return None
#' @examples
#' print_mean_median(df, 'HARRIS'), print_mean_median(df, 'Gore')
print_mean_median <- function(df, candidate)
{
    ucname = toupper(candidate)
    if (ucname %in% colnames(df))
    {
        candidate_summary <- summary(df[ucname])
        sprintf("Candidate %s mean: %s and median: %s", ucname, candidate_summary[mean_idx], candidate_summary[median_idx])
    }
    else 
    {
        sprintf('Candidate name not found, names are case-sensitive: %s', candidate)
    }
}

```

```{r}
# Change column name X to more descriptive COUNTY
print_mean_median(votes, 'buchanan')
print_mean_median(votes, 'nader')
```

```{r}
require('dplyr')
```

```{r}
# Change column X to more descriptive COUNTY and remove BUSH and GORE columns. Use pipes to chain operations
votes <- votes %>% rename( COUNTY = X) %>% select(-BUSH, -GORE)
colnames(votes)

summary(minor_party_candidates)
```

```{r}
# Remove rows - remove counties with fewer than 5000 votes
minor_party_candidates_major_counties <- minor_party_candidates %>% filter(Total >= 5000)

sprintf('Old row count was: %d, New row count is: %d', nrow(minor_party_candidates), nrow(minor_party_candidates_major_counties))

summary(minor_party_candidates_major_counties)
```

```{r}
print_mean_median(minor_party_candidates_major_counties, 'buchanan')
print_mean_median(minor_party_candidates_major_counties, 'nader')
```

```{r}
# Change column values. This data set does not contain any string columns. Instead, replace 0 vote counts in HARRIS column to NA
#head(minor_party_candidates_major_counties)

# Get copy of HARRIS column and modify: replace 0 values with NA
harris_col <- minor_party_candidates_major_counties["HARRIS"]
harris_col[harris_col == 0] <- NA

# Replace HARRIS column in original data frame with modified column
minor_party_candidates_major_counties["HARRIS"] <- harris_col
head(minor_party_candidates_major_counties, 10)
```

